"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, BarChart3 } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/lib/api/client";
type Event = { id?: string; provider?: string; model_code?: string; status?: string; cost_credits?: number; total_tokens?: number; created_at?: string };
type Point = { bucket: string; requests: number; tokens: number; credits: number };
export default function RequestsPage() {
  const [period, setPeriod] = useState("month");
  const events = useQuery({ queryKey: ["admin-requests", period], queryFn: () => api.get<Event[]>("/v1/admin/activity?limit=100") });
  const chart = useQuery({ queryKey: ["admin-request-chart", period], queryFn: () => api.get<Point[]>(`/v1/admin/analytics/timeline?period=${period}`) });
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Requests</h1><p className="mt-1 text-sm text-muted-foreground">Track gateway requests and model activity across Ngamia.</p></div><select value={period} onChange={(event) => setPeriod(event.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="day">Today</option><option value="week">This week</option><option value="month">This month</option><option value="year">This year</option></select></div><Card><CardHeader className="border-b"><CardTitle>Request volume</CardTitle><CardDescription>Live tracked requests by selected period</CardDescription></CardHeader><CardContent className="pt-6">{chart.isLoading ? <Skeleton className="h-52 w-full" /> : <div className="flex h-52 items-end gap-1 rounded-lg bg-muted/30 p-4">{(chart.data ?? []).map((point) => { const max = Math.max(...(chart.data ?? []).map((item) => item.requests), 1); return <div key={point.bucket} className="group flex h-full flex-1 items-end" title={`${point.requests} requests`}><div className="w-full rounded-t-sm bg-primary/75 group-hover:bg-primary" style={{ height: `${Math.max((point.requests / max) * 100, 3)}%` }} /></div> })}</div>}</CardContent></Card><Card><CardHeader className="border-b"><CardTitle>Latest requests</CardTitle><CardDescription>Most recent gateway activity</CardDescription></CardHeader>{events.isLoading ? <CardContent className="space-y-3 py-5">{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="h-10 w-full" />)}</CardContent> : <CardContent className="divide-y p-0">{(events.data ?? []).map((event, index) => <div key={event.id ?? index} className="flex items-center gap-3 p-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-muted"><Activity className="h-4 w-4 text-primary" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{event.model_code ?? "Gateway request"}</p><p className="truncate text-xs text-muted-foreground">{event.provider ?? "Ngamia"} · {event.created_at ? new Date(event.created_at).toLocaleString() : "—"}</p></div><Badge variant={event.status === "completed" ? "secondary" : event.status === "failed" ? "destructive" : "outline"}>{event.status ?? "recorded"}</Badge><span className="hidden text-xs tabular-nums text-muted-foreground sm:block">{(event.cost_credits ?? 0).toLocaleString()} credits</span></div>)}{!events.data?.length && <div className="empty-state"><BarChart3 className="mb-2 h-6 w-6 text-muted-foreground" /><p className="empty-state-title">No requests recorded</p></div>}</CardContent>}</Card></div>;
}
