"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/lib/api/client";
type Profit = { model_code: string; provider: string; request_count: number; total_tokens: number; revenue_credits: number; upstream_cost_credits: number; profit_credits: number; margin_pct: number; upstream_cost_known: boolean };
type Report = { total_revenue_credits: number; total_upstream_cost_credits: number; total_profit_credits: number; margin_pct: number; cost_data_complete: boolean; by_model: Profit[] };
const money = (value: number) => value.toLocaleString(undefined, { maximumFractionDigits: 2 });
export default function ProfitPage() {
  const [period, setPeriod] = useState("month");
  const query = useQuery({ queryKey: ["admin-analytics-profit", period], queryFn: () => api.get<Report>(`/v1/admin/analytics/profit?period=${period}`) });
  const report = query.data;
  const rows = report?.by_model ?? [];
  const max = Math.max(...rows.map((row) => row.revenue_credits), 1);
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Profit report</h1><p className="mt-1 text-sm text-muted-foreground">Revenue, upstream cost, and margin from recorded usage.</p></div><select value={period} onChange={(event) => setPeriod(event.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="day">Today</option><option value="week">This week</option><option value="month">This month</option><option value="year">This year</option></select></div>
    {query.isLoading ? <div className="grid gap-4 sm:grid-cols-4">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-24" />)}</div> : query.isError ? <Card><CardContent className="py-6 text-sm text-destructive">Profit data could not be loaded.</CardContent></Card> : <>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Revenue", report?.total_revenue_credits ?? 0], ["Upstream cost", report?.total_upstream_cost_credits ?? 0], ["Profit", report?.total_profit_credits ?? 0], ["Margin", `${money(report?.margin_pct ?? 0)}%`]].map(([label, value]) => <Card key={label as string}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{typeof value === "string" ? value : money(value as number)}</p><p className="mt-1 text-xs text-muted-foreground">credits, {period}</p></CardContent></Card>)}</div>
    {!report?.cost_data_complete && rows.length > 0 && <p className="text-xs text-amber-600">Some models have no upstream price configured; their profit is an upper-bound estimate.</p>}
    <Card><CardHeader className="border-b"><CardTitle>Revenue by model</CardTitle><CardDescription>Charged credits compared with upstream cost</CardDescription></CardHeader><CardContent className="space-y-4 pt-5">{rows.slice(0, 12).map((row) => <div key={`${row.provider}-${row.model_code}`}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate font-medium">{row.model_code}</span><span className="tabular-nums text-muted-foreground">{money(row.revenue_credits)} credits</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max((row.revenue_credits / max) * 100, row.revenue_credits ? 2 : 0)}%` }} /></div></div>)}{!rows.length && <div className="empty-state"><p className="empty-state-title">No profitability data</p><p className="empty-state-description">Model-level revenue will appear after completed usage is recorded.</p></div>}</CardContent></Card>
    <Card><CardHeader className="border-b"><CardTitle>Model profitability</CardTitle><CardDescription>Completed requests only · all values in credits</CardDescription></CardHeader>
      {rows.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="px-5 py-3 font-medium">Model</th><th className="px-5 py-3 font-medium">Requests</th><th className="px-5 py-3 font-medium">Revenue</th><th className="px-5 py-3 font-medium">Cost</th><th className="px-5 py-3 font-medium">Profit</th><th className="px-5 py-3 font-medium">Margin</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.provider}-${row.model_code}`} className="border-b last:border-0 transition-colors hover:bg-muted/40"><td className="px-5 py-3"><p className="font-medium">{row.model_code}</p><p className="text-xs text-muted-foreground">{row.provider}</p></td><td className="px-5 py-3 tabular-nums">{row.request_count.toLocaleString()}</td><td className="px-5 py-3 tabular-nums">{money(row.revenue_credits)}</td><td className="px-5 py-3 tabular-nums text-muted-foreground">{money(row.upstream_cost_credits)}</td><td className="px-5 py-3 font-medium tabular-nums">{money(row.profit_credits)}</td><td className="px-5 py-3"><Badge variant="outline">{money(row.margin_pct)}%</Badge></td></tr>)}</tbody></table></div> : <CardContent><div className="empty-state"><p className="empty-state-title">No profitability data</p><p className="empty-state-description">Model-level revenue will appear after completed usage is recorded.</p></div></CardContent>}
    </Card></>}
  </div>;
}
