"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Loader2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api, setAdminProfile, setTokens } from "@/lib/api/client";

type Response = { mfa_required?: boolean; mfa_token?: string; user?: { email?: string; full_name?: string; role?: string }; tokens?: { access_token: string; refresh_token: string } };
export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [mfaToken, setMfaToken] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const codeRefs = useRef<Array<HTMLInputElement | null>>([]);
  const finish = (res: Response) => { if (!res.tokens) throw new Error("Incomplete admin session response"); setTokens(res.tokens.access_token, res.tokens.refresh_token); if (res.user) setAdminProfile(res.user); router.replace("/admin"); router.refresh(); };
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const res = await api.post<Response>("/v1/admin/auth/login", { email, password }, { auth: false }); if (res.mfa_required) setMfaToken(res.mfa_token ?? null); else finish(res); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in"); } finally { setLoading(false); } }
  async function verifyCode(value: string) { if (!mfaToken || loading) return; setLoading(true); setError(null); try { finish(await api.post<Response>("/v1/admin/auth/mfa/verify", { mfa_token: mfaToken, code: value }, { auth: false })); } catch (e) { setError(e instanceof Error ? e.message : "Invalid MFA code"); setCode(""); codeRefs.current[0]?.focus(); } finally { setLoading(false); } }
  async function verify(event: React.FormEvent) { event.preventDefault(); await verifyCode(code); }
  useEffect(() => { if (mfaToken) codeRefs.current[0]?.focus(); }, [mfaToken]);
  function updateCode(value: string, index: number) { const digits = value.replace(/\D/g, ""); if (!digits) return; const next = (code.slice(0, index) + digits).slice(0, 6); setCode(next); codeRefs.current[Math.min(index + digits.length, 5)]?.focus(); if (next.length === 6) void verifyCode(next); }
  function handleCodeKey(event: React.KeyboardEvent<HTMLInputElement>, index: number) { if (event.key === "Backspace" && !code[index] && index > 0) codeRefs.current[index - 1]?.focus(); if (event.key === "ArrowLeft" && index > 0) codeRefs.current[index - 1]?.focus(); if (event.key === "ArrowRight" && index < 5) codeRefs.current[index + 1]?.focus(); }
  return <div className="auth-shell"><div className="auth-card"><div className="auth-lockup"><Image src="/logo-512.png" alt="Ngamia" width={36} height={36} className="rounded-lg" /><span className="text-lg font-semibold tracking-tight">Ngamia Admin</span></div><h1 className="auth-card-heading">{mfaToken ? "Verify your identity" : "Administrator sign in"}</h1><p className="auth-card-subtext">{mfaToken ? "Enter the 6-digit code from your authenticator app." : "Secure access to platform operations."}</p><div className="auth-form">{error && <div className="callout callout-danger mb-4">{error}</div>}{mfaToken ? <form onSubmit={verify} className="flex flex-col gap-4"><div><Label htmlFor="mfa-code-0">Authenticator code</Label><div className="mt-2 flex justify-between gap-2" onPaste={(event) => { event.preventDefault(); updateCode(event.clipboardData.getData("text"), 0); }}>{Array.from({ length: 6 }, (_, index) => <Input key={index} ref={(element) => { codeRefs.current[index] = element; }} id={`mfa-code-${index}`} aria-label={`Authenticator digit ${index + 1}`} inputMode="numeric" maxLength={1} value={code[index] ?? ""} onChange={(event) => updateCode(event.target.value, index)} onKeyDown={(event) => handleCodeKey(event, index)} className="h-11 w-11 p-0 text-center text-xl font-semibold" />)}</div></div><Button type="submit" disabled={loading || code.length !== 6} className="h-10 w-full">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{loading ? "Verifying…" : "Verify and continue"}</Button><button type="button" className="text-sm text-muted-foreground underline" onClick={() => { setMfaToken(null); setCode(""); }}>Use a different account</button></form> : <form onSubmit={submit} className="flex flex-col gap-4"><div><Label htmlFor="email">Admin email</Label><Input id="email" type="email" autoComplete="username" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1.5" required /></div><div><Label htmlFor="password">Password</Label><Input id="password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1.5" required /></div><Button type="submit" disabled={loading} className="h-10 w-full">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{loading ? "Signing in…" : "Sign in securely"}</Button></form>}</div><p className="mt-6 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4" /> Administrator accounts only</p></div></div>;
}
