"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, CreditCard } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/lib/api/client";
type Payment = { id: string; provider?: string; provider_reference?: string; amount_tzs: number; status: string; created_at: string; user_id?: string; user_name?: string; user_email?: string; user_phone?: string };
export default function PaymentDetailPage() { const { id } = useParams<{ id: string }>(); const query = useQuery({ queryKey: ["admin-payment", id], queryFn: () => api.get<Payment>(`/v1/admin/payments/${id}`), enabled: !!id }); const p = query.data; return <div className="space-y-5"><Button variant="ghost" size="sm" render={<Link href="/admin/payments" />}><ArrowLeft className="mr-2 h-4 w-4" />Payments</Button><div><h1 className="text-2xl font-semibold tracking-tight">Payment detail</h1><p className="mt-1 text-sm text-muted-foreground">Full settlement and customer record.</p></div>{query.isLoading ? <Skeleton className="h-64 w-full" /> : query.isError || !p ? <Card><CardContent className="py-8 text-sm text-destructive">Payment could not be loaded.</CardContent></Card> : <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><CreditCard className="h-4 w-4 text-primary" />Transaction</CardTitle><CardDescription>{p.provider_reference ?? p.id}</CardDescription></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Amount</p><p className="font-semibold">{p.amount_tzs.toLocaleString()} TZS</p></div><div><p className="text-xs text-muted-foreground">Status</p><Badge className="mt-1 capitalize">{p.status}</Badge></div><div><p className="text-xs text-muted-foreground">Provider</p><p>{p.provider ?? "—"}</p></div><div><p className="text-xs text-muted-foreground">Created</p><p>{new Date(p.created_at).toLocaleString()}</p></div></CardContent></Card><Card><CardHeader className="border-b"><CardTitle>Customer</CardTitle><CardDescription>Account attached to this payment</CardDescription></CardHeader><CardContent className="space-y-3 p-5"><div><p className="text-xs text-muted-foreground">Name</p><p className="font-medium">{p.user_name ?? "—"}</p></div><div><p className="text-xs text-muted-foreground">Email</p><p>{p.user_email ?? "—"}</p></div><div><p className="text-xs text-muted-foreground">Phone</p><p>{p.user_phone ?? "—"}</p></div><div><p className="text-xs text-muted-foreground">User ID</p><p className="break-all font-mono text-xs">{p.user_id ?? "—"}</p></div></CardContent></Card></div>}</div>; }
